services:
  api:
    container_name: etl_kafka_transform
    image: markreduce/etl:kafkatransform
    env_file:
      - .env
    networks:
      kafka:
networks:
  kafka:
    name: kafka
    external: true