services:
  scrapping:
    container_name: scrapping
    image: markreduce/etl:webscrapping
    build:
      context: .
    volumes:
      - scrap_logs:/usr/src/app/logs
    environment:
      LOG_FILE: ./logs/.log
volumes:
  scrap_logs:
    name: "scrap_logs"