services:
  scrapping:
    container_name: scrapping
    image: markreduce/etl:webscrapping
    env_file:
      - .env
networks:
  kafka:
    name: kafka
    external: true
# volumes:
#   scrap_logs:
#     name: "scrap_logs"