services:
  scrapping:
    container_name: scrapping
    image: markreduce/etl:webscrapping
    build:
      context: .
    volumes:
      - scrap_logs:/usr/src/app/logs
      - debug:/root/
    environment:
      LOG_FILE: ./logs/.log
      DRIVER_PATH: ./utils/chromedriver
volumes:
  scrap_logs:
    name: "scrap_logs"
  debug:
    name: "debug"