set POSTGRES_DB=CDC_DB
set POSTGRES_USER=CDC_USER
set POSTGRES_PASSWORD=kakarott
set POSTGRES_PORT=6432
set SLOT_NAME=translation
set PUBLICATION_NAME=cdc_translation
set DEBEZIUM_USER=CDC_USER
set DEBEZIUM_PASSWORD=kakarott