services:
  connect:
    container_name: connect
    image: quay.io/debezium/connect:2.5
    environment:
      - CONFIG_STORAGE_TOPIC=pg_cdc
      - OFFSET_STORAGE_TOPIC=pg_offset
      - STATUS_STORAGE_TOPIC=pg_status
      - BOOTSTRAP_SERVERS=broker1:29092
    ports:
      - 127.0.0.1:8083:8083 # to use Connect Rest API endpoint for other applications
    networks:
      kafka:

networks:
  kafka:
    name: kafka
    external: true