networks:
  kafka:
    external: true
services:
  node-1:
    image: cassandra:latest
    container_name: node-1
    ports:
      - 127.0.0.1:7000:7000
      - 127.0.0.1:9042:9042
    environment:
      CASSANDRA_CLUSTER_NAME: my-cluster
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_DC: my-datacenter
      CASSANDRA_BROADCAST_ADDRESS: node-1
    networks:
      - kafka
    
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3

  node-2:
    image: cassandra:latest
    container_name: node-2
    ports:
      - 127.0.0.1:9043:9042
    environment:
      CASSANDRA_CLUSTER_NAME: my-cluster
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_DC: my-datacenter
      CASSANDRA_SEEDS: node-1
    networks:
      - cassandra
    
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3
      
    depends_on:
      node-1:
        condition: service_healthy

  node-3:
    image: cassandra:latest
    container_name: node-3
    environment:
      CASSANDRA_CLUSTER_NAME: my-cluster
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_DC: my-datacenter
      CASSANDRA_SEEDS: node-1
    ports:
      - 127.0.0.1:9044:9042
    networks:
      - cassandra
    
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3

    depends_on:
      node-2:
        condition: service_healthy