services:
  zookeeper:
    container_name: zookeeper
    image: quay.io/debezium/zookeeper:3.0

  broker1: 
    container_name: broker1
    hostname: broker1
    image: quay.io/debezium/kafka:3.0
    ports:
      - 127.0.0.1:29092:29092 
    environment:
      - BROKER_ID=1
      - ZOOKEEPER_CONNECT=zookeeper
    depends_on:
      - zookeeper

  broker2: 
    container_name: broker2
    hostname: broker2
    image: quay.io/debezium/kafka:3.0
    ports:
      - 127.0.0.1:9092:9092 
    environment:
      - BROKER_ID=2
      - ZOOKEEPER_CONNECT=zookeeper
    depends_on:
      - zookeeper

  broker3: 
    container_name: broker3
    hostname: broker3
    image: quay.io/debezium/kafka:3.0
    ports:
      - 127.0.0.1:9093:9092 # open port 9092 however it is not necessary 
    environment:
      - BROKER_ID=3
      - ZOOKEEPER_CONNECT=zookeeper
    depends_on:
      - zookeeper