services:
  cdc_database:
    container_name: cdc_db
    image: postgres:12-alpine
    ports:
      - 127.0.0.1:6432:5432
    env_file:
      - .env
    volumes:
      - cdc-data:/var/lib/postgresql/data
    networks:
      kafka:
volumes:
  cdc-data:
    name: "cdc-data"

networks:
  kafka:
    name: kafka
    external: true