services:
  file:
    container_name: sftp
    image: markreduce/etl:file
    volumes:
      - sftp_key:/home/ubuntu:ro # private key 
    env_file:
      - .env
volumes:
  sftp_key:
    name: sftp_key
    external: true